name: Create a zipped lambda func for deployment

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # push events to matching v*

jobs:
  build:
    runs-on: ubuntu-latest
    # create the zip file
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Lambda Function
        run: |
          zip lambda.zip rolling-restart.py
          ls

      - name: Get tag 
        id: get_tag
        run: |
          echo ::set-output name=VTAG::$( echo $GITHUB_REF | cut -d / -f 3 )

      - name: Upload lambda to assets
        id: upload-lambda-asset
        uses: AButler/upload-release-assets@v2.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          files: '*.zip'
          release-tag: ${{ steps.get_tag.outputs.VTAG }}
