name: release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    # create the zip file
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Lambda Function
        run: |
          zip lambda.zip rolling-restart.py
          ls

      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: lambda.zip
          path: ${{ github.workspace }}/lambda.zip
          if-no-files-found: error

      - name: get checksum
        run: cat lambda.zip | openssl dgst -binary -sha256 | base64 > lambda.sha256sum.base64

      - name: Upload zip
        id: upload-zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./lambda.zip
          asset_name: lambda.zip
          asset_content_type: application/zip

      - name: Upload shasum
        id: upload-shasum
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./lambda.sha256sum.base64
          asset_name: lambda.sha256sum.base64
          asset_content_type: text/plain
