name: Create a zipped lambda func for deployment

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # push events to matching v*

jobs:
  build:
    runs-on: ubuntu-latest
    # create the zip file
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Lambda Function
        run: |
          zip lambda.zip rolling-restart.py

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload lambda to assets
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./lambda.zip
          asset_name: lambda.zip
          asset_content_type: application/zip
